export const VALIDATE_FORM_NEW_PRODUCT = 'VALIDATE_FORM_NEW_PRODUCT';
export const VALIDATE_FORM_NEW_PRODUCT_SUCCESS = 'VALIDATE_FORM_NEW_PRODUCT_SUCCESS';
export const VALIDATE_FORM_NEW_PRODUCT_ERROR = 'VALIDATE_FORM_NEW_PRODUCT_ERROR';

export const ADD_PRODUCT = 'ADD_PRODUCT';
export const ADD_PRODUCT_SUCCESS = 'ADD_PRODUCT_SUCCESS';
export const ADD_PRODUCT_ERROR = 'ADD_PRODUCT_ERROR';

export const INIT_DOWNLOAD_PRODUCTS = 'INIT_DOWNLOAD_PRODUCTS';
export const DOWNLOAD_PRODUCTS_SUCCESS = 'DOWNLOAD_PRODUCTS_SUCCESS';
export const DOWNLOAD_PRODUCTS_ERROR = 'DOWNLOAD_PRODUCTS_ERROR';