export const VALIDATE_FORM_NEW_PRODUCT = 'VALIDATE_FORM_NEW_PRODUCT';
export const VALIDATE_FORM_NEW_PRODUCT_SUCCESS = 'VALIDATE_FORM_NEW_PRODUCT_SUCCESS';
export const VALIDATE_FORM_NEW_PRODUCT_ERROR = 'VALIDATE_FORM_NEW_PRODUCT_ERROR';

export const ADD_PRODUCT = 'ADD_PRODUCT';
export const ADD_PRODUCT_SUCCESS = 'ADD_PRODUCT_SUCCESS';
export const ADD_PRODUCT_ERROR = 'ADD_PRODUCT_ERROR';

export const INIT_DOWNLOAD_PRODUCTS = 'INIT_DOWNLOAD_PRODUCTS';
export const DOWNLOAD_PRODUCTS_SUCCESS = 'DOWNLOAD_PRODUCTS_SUCCESS';
export const DOWNLOAD_PRODUCTS_ERROR = 'DOWNLOAD_PRODUCTS_ERROR';

export const GET_PRODUCT_TO_DELETE = 'GET_PRODUCT_TO_DELETE';
export const DELETE_PRODUCT_SUCCESS = 'DELETE_PRODUCT_SUCCESS';
export const DELETE_PRODUCT_ERROR = 'DELETE_PRODUCT_ERROR';

export const GET_PRODUCT_TO_EDIT = 'GET_PRODUCT_TO_EDIT';
export const GET_PRODUCT_TO_EDIT_SUCCESS = 'GET_PRODUCT_TO_EDIT_SUCCESS';
export const GET_PRODUCT_TO_EDIT_ERROR = 'GET_PRODUCT_TO_EDIT_ERROR';

export const INIT_EDIT_PRODUCT = 'INIT_EDIT_PRODUCT';
export const EDIT_PRODUCT_SUCCESS = 'EDIT_PRODUCT_SUCCESS';
export const EDIT_PRODUCT_ERROR = 'EDIT_PRODUCT_ERROR';